version: "3.8"
services:
  sam-local:
    build:
      context: .
      dockerfile: ./docker/sam-local/Dockerfile
    ports:
      - 3001:3001
    working_dir: $PWD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:$PWD
    command: >
      sam local start-lambda
        --host 0.0.0.0
        --container-host host.docker.internal
        --docker-network aws-sfn-local_default

  sfn-local:
    image: localstack/localstack
    ports:
      - 8083:4566
    environment:
      DEBUG: 1
      DATA_DIR: /tmp/localstack/data
      SERVICES: ssm,stepfunctions
      DEFAULT_REGION: ap-northeast-1
      STEPFUNCTIONS_LAMBDA_ENDPOINT: http://sam-local:3001
    volumes:
      - ./docker/localstack/initaws:/docker-entrypoint-initaws.d
